[workspace]
authors = ["Samuel Klein <samuel.byrne.klein@gmail.com>"]
channels = ["conda-forge"]
name = "test_pixi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
